### ISSUE TITLE
How can i change compliments?

### ISSUE THREAD

**Issue by dersch81** [bastilimbach/docker-MagicMirror#10]
Hi, i've switching from standalone pi to a docker mirror. It is running now, but i had a custom compliments file. I included that to my custom folder of modules as i did that with the standalone MM. But how will this affect any updating? In the past i had to change the compliments.js to the original version to update my mirror via git.

**Comment by bastilimbach** [comment]
If I'm correct you can include the compliments either in the `config.js` file or in a external file. If you include the compliments directly into the `config.js` or the external file is in the `config` or `modules` folder, they won't get overridden on an update. **It's important, that you [add these as volumes](https://github.com/bastilimbach/docker-MagicMirror#volumes)!**

**Comment by dersch81** [comment]
Ok thanks a lot. Would this be the same dir changes in a CSS file for the Mirror? As suggested by the rtspstream Module maintainer i need a CSS change:

~/MagicMirror/css/custom.css file.

```css
.MMM-RTSPStream .innerWrapper {
  margin: 0px;
}
```

**Comment by bastilimbach** [comment]
Oh ok, that's something I didn't consider. It was new to me, that you could write your own custom css in `css/custom.css`. Theoretically, it should work if you mount the `css/custom.css` file using volumes:

```bash
--volume ~/your/path/custom.css:/opt/magic_mirror/css/custom.css
```

I'll take a look at this and update the README if it works as expected.

**Comment by bastilimbach** [comment]
@dersch81 I updated the README to reflect this use case (1e14e332ebbf17504863036d1e7521700046d70c). I tested it yesterday and it worked as expected. 👍It's important, that you create your `custom.css` file before you mount/run the container. I hope this helps you. If you have any further questions, please feel free to reopen this issue.

**Comment by dersch81** [comment]
Thanks a lot! I'm actually playing around with it. 

- I need to add the main.css as well to the volume, right? I couldn't get the mirror working correctly without this. 
- If I change the custom.css file i need to stop/start the container or do I need to create it again? (docker stop/rm/run)

My change of the custom.css doesn't change anything acutally. 
```css
/*****************************************************
 * Magic Mirror                                      *
 * Custom CSS                                        *
 *                                                   *
 * By Michael Teeuw http://michaelteeuw.nl           *
 * MIT Licensed.                                     *
 *                                                   *
 * Add any custom CSS below.                         *
 * Changes to this files will be ignored by GIT. *
 *****************************************************/

body {
  .MMM-RTSPStream .innerWrapper {
    margin: 0px;
  }
}
```

**Comment by bastilimbach** [comment]
If you mount the `/css` folder you need to copy the `main.css` and `custom.css` file manually into it, correct. If you just mount the `custom.css` file instead of the whole folder, you don't need to do anything with the `main.css` file.

Your css changes aren't working, because they are not correct. In normal CSS you can not nest rules. This only works in [SASS](https://sass-lang.com/) for example. 

It should be:
```css
/*****************************************************
 * Magic Mirror                                      *
 * Custom CSS                                        *
 *                                                   *
 * By Michael Teeuw http://michaelteeuw.nl           *
 * MIT Licensed.                                     *
 *                                                   *
 * Add any custom CSS below.                         *
 * Changes to this files will be ignored by GIT. *
 *****************************************************/

body {
  /* only things you want to change on the 'body' element (eg: background: red;) */
}

.MMM-RTSPStream .innerWrapper {
  margin: 0px;
}
```

Theoretically, you don't need to restart the container, if you change the css. You only need to restart the container, if you change the `config.js` file or add a new module into the modules folder.
