### ISSUE TITLE
MagicMirror: v2.3.1  pls update zu v2.4

### ISSUE THREAD

**Issue by Jan-2005** [bastilimbach/docker-MagicMirror#12]
I have just installed Magic mirror per docker. The config is not recognized. I can not install any other modules.

Can you help me.
have heard of the latest version should be fixed. Greeting Jan

**Comment by bastilimbach** [comment]
The image gets updated every day by a cron job from Travis CI. It should already be the latest MagicMirror version. What exactly is your problem? Could you post some logs/error messages?

**Comment by Jan-2005** [comment]
```bash      
Starting MagicMirror: v2.3.1
Loading config ...
WARNING! Could not find config file. Please create one. Starting with default configuration.
ading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
l module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...
Ready to go! Please point your browser to: http://localhost:8080
```

**Comment by Jan-2005** [comment]
```javascript
var config = {
	address: "",
	port: 8080,
	ipWhitelist: [],
	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "clock",
			position: "top_left"
		}
	]

};
```

**Comment by Jan-2005** [comment]
With docker-compose.yml 

```yaml
version: '2'

services:
    fhem:
        restart: always
        expose:
            - "8083"
            - "7072"
            - "8383"
        ports:
            - "8383:8383"
            - "8083:8083"
            - "7072:7072"
        build: fhem
        privileged: true
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            - ./fhem/core/:/opt/fhem/
            - /dev/serial/by-id:/dev/serial/by-id

        networks:
            - fhem-network
        depends_on:
            - "mysql"
            - "mqtt"
            - "smartvisu"


          

    homebridge:
        restart: always
        image: oznu/homebridge
        volumes:
            - ./homebridge/config.json:/homebridge/config.json
            - ./homebridge/package.json:/homebridge/package.json
        environment:
            - TZ=Europe/Berlin
            - PGID=1000
            - PUID=1000
        network_mode: host
        depends_on:
            - "fhem"

    habridge:
        restart: always
        build: habridge
        network_mode: host

    mysql:
        restart: always
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mqtt/config/
            - ./mqtt/log/:/mqtt/log/
            - ./mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:0.18.4
        volumes:
            - ./nodered/data/:/root/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"
    

    smartvisu:
        restart: always
        image: foxi352/smartvisu
        volumes:
            - ./fhem//core/www/smartvisu2.8/:/var/www/html
        ports: 
            - "8082:81"
        networks:
            - fhem-network

    
    
    portainer:
        restart: always
        image: portainer/portainer
        volumes:
           - ./portainer/:/data
           - /var/run/docker.sock:/var/run/docker.sock
        ports:
           - "9000:9000"

    magic_mirror:
        restart: always
        image: bastilimbach/docker-magicmirror
        expose:
            - "8080"
        ports:
            - "8080:8080"
        volumes:
            - ./magic_mirror/config:/opt/magic_mirror/config \
            - ./magic_mirror/modules:/opt/magic_mirror/modules \
            - ./magic_mirror/css:/opt/magic_mirror/css/custom.css \
        networks:
            - fhem-network

    alexa:
       restart: always
       
       expose: 
            - "3000"
       ports:
            - "3000:3000"
       image: bananarama/x86-alexa-fhem:latest
      
       volumes:
            - ./alexa/config:/config
            
       networks:
            - fhem-network
       depends_on:
            - "fhem"

networks:
        fhem-network:
            driver: bridge
```

config not Found
